### ISSUE TITLE
CO002 Filtros de usuarios

### ISSUE THREAD

**Issue by AnnBenavides** [AnnBenavides/coins#29]
- [ ] ***getProfesores()*** : retorna una _lista de usuarios_ profesores con su url a foto, nombre y taller (#18)
- [ ] ***getAlumnosTaller(String nombreTaller)*** : retorna una _lista de usuarios_ alumnos  que están en ese taller, entregando su foto, nombre y número de grupo (#18)
- [ ] ***getProfesor(int id)***: retorna el usuario profesor correspondiente a dicha id, y entrega su foto, nombre y taller que imparte. (#21)
- [ ] ***getAlumno(int id)***: retorna el usuario alumno correspondiente a dicha id, y entrega su foto, nombre, taller y grupo. (#22)
