### ISSUE TITLE
CO003 Flujos de Coins

### ISSUE THREAD

**Issue by AnnBenavides** [AnnBenavides/coins#30]
# Gastos
- [ ] **comprarBloque(int idBloque, int idAlumno):** (#21) acción de compra de un bloque por un alumno
  - Descuenta coins al alumno (billetera.saldo)
  - Agrega coins al profesor (billetera.saldo)
  - Cambia el estado del bloque (bloque.estado) a comprado
  - Asignar grupo al que pertenece el alumno (usuario.grupo)
  - Agrega transacción al historial

- [ ] **comprarAyuda(int idVendedor, int idComprador):** (#22) acción de compra de una unidad de ayuda entre alumnos.
  - Descuenta coins al comprador
  - Carga coins al vendedor
  - Agrega transacción al historial

# Cargos
- [ ] **cargarCoins(int idAlumno, int coins):** (#24)
  - Cargar coins al alumno

# Informativos
- [ ] **getSaldo(int idAlumno)**
- [ ] **getCostoBloque(int idBloque)**
